### ISSUE TITLE
Don't work without debug info enabled

### ISSUE THREAD

**Issue by petercrona** [GabrielDelepine/angular-css-injector#22]
Hello,

The CSS injector does not work disabling debug info with: $compileProvider.debugInfoEnabled(false);
(https://docs.angularjs.org/guide/production).

The problem is "head.scope();". A workaround is simply using $rootScope. 
So instead of setting scope = head.scope(); always setting "scope = $rootScope" seems to solve the problem.

Kind regards 
Peter

**Comment by Ricardo-Marques** [comment]
This is still an issue but _only_ using the minified version. Seems like the minified and unminified files are not in sync as of today.

**Comment by GabrielDelepine** [comment]
Hi,
Sorry, this repository is not maintained anymore.
One of the fork is probably more appropriate. If you know one, let me know I will put the link in the readme.
Thanks
