### ISSUE TITLE
cssInjectorProvider.setSinglePageMode is not working

### ISSUE THREAD

**Issue by alexanderpa** [GabrielDelepine/angular-css-injector#24]
There is no possibility to set singlePageMode from provider on config phase.

In your plugin singlePageMode variable defined twice. 
Provider modified global variable and in service you use local variable.

**Comment by stsatlantis** [comment]
is it fixed?

**Comment by GabrielDelepine** [comment]
Hi,
Sorry, this repository is not maintained anymore.
One of the fork is probably more appropriate. If you know one, let me know I will put the link in the readme.
Thanks
