### ISSUE TITLE
check version

### ISSUE THREAD

**Issue by pvnr0082t** [GabrielDelepine/angular-css-injector#30]
Hi @GabrielDelepine ,
I want to add this library to [cdnjs](https://github.com/cdnjs/cdnjs) via send PR.
I found that the git tags show v1.4.0, but the ```angular-css-injector.js``` and ```angular-css-injector.min.js``` are both v1.0.4. 
Please check the version, thank you.

https://github.com/cdnjs/cdnjs/issues/7598

**Comment by germanger** [comment]
had the same problem today (july 12)

**Comment by GabrielDelepine** [comment]
Hi,
Sorry, this repository is not maintained anymore.
One of the fork is probably more appropriate. If you know one, let me know I will put the link in the readme.
Thanks
