### ISSUE TITLE
Add angular-css-injector to NPM

### ISSUE THREAD

**Issue by AmitMY** [GabrielDelepine/angular-css-injector#31]
Please add angular-css-injector to NPM

**Comment by m0ngr31** [comment]
And bower

**Comment by GabrielDelepine** [comment]
Hi,
Sorry, this repository is not maintained anymore.
One of the fork is probably more appropriate. If you know one, let me know I will put the link in the readme.
Thanks

**Comment by AmitMY** [comment]
@GabrielDelepine Thanks, was nice working with it for a while, did a lot of stuff right!
