### ISSUE TITLE
CSS isn't re-injected after state change when single page mode is enabled

### ISSUE THREAD

**Issue by dciq** [GabrielDelepine/angular-css-injector#34]
I'm working on a project that is using ui-router. I want to use css-injector for state specific views.

The injector successfully injects my css files when I first land on a page. However, if I navigate away and then back to a page, the css is no longer injected. A hard reload fixes the issue.

Has anyone dealt with a similar issue? Does anyone have any ideas on how to resolve this?

**Comment by Jay-Tanwar** [comment]
Possibly the CSS is getting cached by the browser.
A temporary solution would be to add a timestamp querystring to the css file so that its fetched fresh from server each time.

**Comment by GabrielDelepine** [comment]
Hi,
Sorry, this repository is not maintained anymore.
One of the fork is probably more appropriate. If you know one, let me know I will put the link in the readme.
Thanks
